# Generated by Django 3.0.4 on 2020-03-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Cedula', models.IntegerField()),
                ('Direccion', models.CharField(max_length=30)),
                ('Colegio_Electoral', models.IntegerField()),
                ('Centro_De_Votacion', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=13)),
                ('Telefono', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Necesita_Tras', models.CharField(max_length=3)),
                ('Edad', models.IntegerField()),
                ('Sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('user_parent', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
