# Generated by Django 3.0.4 on 2020-03-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFormulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='Necesita_Tras',
        ),
    ]
