# Generated by Django 3.0.4 on 2020-04-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFormulario', '0002_remove_personas_necesita_tras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='Rol',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_parent',
            new_name='User_parent',
        ),
    ]
