# Generated by Django 3.0.4 on 2020-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFormulario', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Direccion',
            field=models.CharField(max_length=130),
        ),
    ]
