# Generated by Django 3.0.4 on 2020-04-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFormulario', '0005_auto_20200413_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Cedula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Colegio_Electoral',
            field=models.CharField(max_length=50),
        ),
    ]
