# Generated by Django 3.0.4 on 2020-04-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFormulario', '0011_auto_20200420_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='Centro_De_Votacion',
            new_name='CentroDeVotacion',
        ),
    ]
